# Generated by Django 6.0 on 2025-12-08 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GBVReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_violence', models.CharField(choices=[('physical', 'Physical Violence'), ('sexual', 'Sexual Violence'), ('emotional', 'Emotional/Psychological Violence'), ('economic', 'Economic Violence'), ('digital', 'Digital/Online Violence'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(help_text='County, town, or area', max_length=255)),
                ('details', models.TextField(help_text='Detailed description of the incident')),
                ('incident_date', models.DateField(blank=True, help_text='Date when the incident occurred', null=True)),
                ('file_upload', models.FileField(blank=True, help_text='Optional: Upload evidence (photos, documents, etc.)', null=True, upload_to='reports/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use only', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GBV Report',
                'verbose_name_plural': 'GBV Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lawyer or firm name', max_length=255)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number (optional)', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('county', models.CharField(help_text='County where services are provided', max_length=100)),
                ('specialization', models.CharField(help_text='Specialization areas (e.g., GBV cases, family law, criminal law)', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Physical address (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this lawyer currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lawyer',
                'verbose_name_plural': 'Lawyers',
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', unique=True)),
                ('content', models.TextField(help_text='Full article content (HTML allowed)')),
                ('category', models.CharField(choices=[('rights', 'Know Your Rights'), ('complaint', 'How to File a Complaint'), ('emergency', 'Emergency Steps'), ('support', 'Support Services'), ('prevention', 'Prevention'), ('other', 'Other')], default='other', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource Article',
                'verbose_name_plural': 'Resource Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Therapist or counselor name', max_length=255)),
                ('specialty', models.CharField(help_text='Specialty areas (e.g., trauma counseling, PTSD, domestic violence, anxiety)', max_length=255)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('county', models.CharField(help_text='County where services are provided', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Physical address or clinic name (optional)', null=True)),
                ('qualifications', models.CharField(blank=True, help_text='Professional qualifications (optional)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this therapist currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Therapist',
                'verbose_name_plural': 'Therapists',
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
